### ISSUE TITLE
404 on any request to v1.0.0-beta10 via HTTP proxy

### ISSUE THREAD

**Issue by IKSIN** [Comcast/trickster#355] opened 2020-02-04 14:41 UTC
Hello! We use http proxy to k8s ingress, therefore, when I try to use prometheus.example.org (DNS record see to nginx) they resolved to proxy IP. Trickster proxy use IP address to send requests to prometheuses?

**Comment by IKSIN** [comment] 2020-02-04 14:48
Sorry, all is well

**Comment by jranson** [comment] 2020-02-09 23:27
@IKSIN Thanks for this report. We have isolated the root cause of this and a patch will be included in 1.0-rc2.

**Comment by jranson** [comment] 2020-02-09 23:50
Will reopen this until we have the release cut.

**Comment by jranson** [comment] 2020-02-10 04:55
@IKSIN we have this all fixed up in 1.0.0-rc2, thanks again!

**Closed by jranson** 2020-02-10 04:55 UTC
Labels: 1.0 release, bug, http-proxy
