### ISSUE TITLE
Query errors from Grafana using Trickster 1.0.9-beta 

### ISSUE THREAD

**Issue by vitovitolo** [Comcast/trickster#271] opened 2019-08-30 09:32 UTC
We've recently upgrade trickster from `0.1.10` to `1.0.9-beta` and we are experienced some errors while loading Grafana dashboards. Errors are intermittent, sometimes it works perfect.

Our setup is built on k8s:
- prometheus Statefulset with 1 replica and a cloud storage volume + Service
- trickster Statefulset with 5 replicas each with a cloud storage volume using BoltDB + Service
- Ingress exposing trickster k8s Service as a Grafana Datasource

- prometheus version 2.10.0
- trickster version 1.0.9-beta
- trickster `/etc/trickster/trickster.conf` configMap
```
    [main]
    [proxy_server]
        listen_port = 9092 # To avoid collision with prometheus port 9090. The port 9092 is unallocated by the community to avoid collisions with kafka but we're not going to have this problem inside our replication controller.

    [cache]
        [caches.default]
                # Options are 'boltdb, 'filesystem', 'memory', and 'redis'
                cache_type = 'bbolt'

                # timeseries_ttl_secs defines the relative expiration of cached timeseries. default is 6 hours (21600 seconds)
                timeseries_ttl_secs = 21600

                    # Configuration options when using a BoltDb Cache
                    [cache.bbolt]

                    # filename defines the file where the Trickster cache will be maintained
                    # default is 'trickster.db'
                    filename = '/tmp/trickster/trickster.db'
                    # filename = 'trickster.db'

                    # bucket defines the name of the BotlDb bucket (similar to a namespace) under which our key value store lives
                    # default is 'trickster'
                    # bucket = 'trickster'
                [caches.default.index]

                # reap_interval_secs defines how long the Cache Index reaper sleeps between reap cycles. Default is 3 (3s)
                reap_interval_secs = 3

                # flush_interval_secs sets how often the Cache Index saves its metadata to the cache from application memory. Default is 5 (5s)
                flush_interval_secs = 5

                # max_size_bytes indicates how large the cache can grow in bytes before the Index evicts least-recently-accessed items. default is 512MB
                max_size_bytes = 536870912

                # max_size_backoff_bytes indicates how far below max_size_bytes the cache size must be to complete a byte-size-based eviction exercise. default is 16MB
                max_size_backoff_bytes = 16777216

                # max_size_objects indicates how large the cache can grow in objects before the Index evicts least-recently-accessed items. default is 0 (infinite)
                max_size_objects = 0

                # max_size_backoff_objects indicates how far under max_size_objects the cache size must be to complete object-size-based eviction exercise. default is 100
                max_size_backoff_objects = 100


    # Configuration options for mapping Origin(s)
    [origins]
        [origins.default]
            cache_name = 'default'
            host = 'prometheus-server.prometheus-runtime.svc:9090'
            api_path = '/api/v1'
            ignore_no_cache_header = false
            # 30 days is the max age of specific datapoints in the cache.
            max_value_age_secs = 2592000
            # timeseries_eviction_method selects the metholodogy used to determine which timestamps are removed once
            # the timeseries_retention_factor limit is reached. options are 'oldest' and 'lru'. Default is 'oldest'
            timeseries_eviction_method = 'lru'

    [metrics]
        listen_port = 8082

    [logging]

        # Possible values are 'debug', 'info', 'warn', 'error'
        log_level = 'debug'
```

I attached trickster debug level logs but I can't see any errors:

[trickster_1.0.9-beta.log](https://github.com/Comcast/trickster/files/3559236/trickster_1.0.9-beta.log)

It seems like those requests are timing out from client perspective because trickster cannot handled properly. ingress-nginx logs with requests who end up in trickster:

```
[27/Aug/2019:14:47:02 +0000] "GET /api/v1/query_range?end=2019-08-27T14%3A46%3A32.362558337Z&query=nomad_allocation_memory_rss_bytes%7Bexported_job%3D%22corporate%22%2C+environment%3D%22production%22%7D&start=2019-08-27T14%3A41%3A32.362558337Z&step=15.000 HTTP/1.1" 499 0 "-" "Go-http-client/1.1" 348 29.977 [prometheus-runtime-trickster-9092] 192.168.41.172:9092 0 29.978 - e083e992b05fe983516842c43e94d132 trickster-grafana-prometheus-runtime.otters.xyz
[27/Aug/2019:14:47:02 +0000] "GET /api/v1/query_range?end=2019-08-27T14%3A46%3A32.363149021Z&query=nomad_allocation_memory_rss_bytes%7Bexported_job%3D%22enterprise%22%2C+environment%3D%22production%22%7D&start=2019-08-27T14%3A41%3A32.363149021Z&step=15.000 HTTP/1.1" 499 0 "-" "Go-http-client/1.1" 349 29.995 [prometheus-runtime-trickster-9092] 192.168.41.170:9092 0 29.995 - 5a9582b2459d6f8bdd41c12141b14754 trickster-grafana-prometheus-runtime.otters.xyz
[27/Aug/2019:14:47:02 +0000] "GET /api/v1/query_range?end=2019-08-27T14%3A46%3A32.415138983Z&query=nomad_allocation_memory_rss_bytes%7Bexported_job%3D%22corporate%22%2C+environment%3D%22production%22%7D&start=2019-08-27T14%3A41%3A32.415138983Z&step=15.000 HTTP/1.1" 499 0 "-" "Go-http-client/1.1" 348 29.982 [prometheus-runtime-trickster-9092] 192.168.41.172:9092 0 29.982 - 60fb84b62a890778ec573ea876f75411 trickster-grafana-prometheus-runtime.otters.xyz
```

`trickster_proxy_failed_connections_total` metric keep it at 0 value all the time.

Could someone give some light about what's happening?

Thanks in advance

**Comment by pcarranza** [comment] 2019-08-30 10:52
`trickster_proxy_failed_connections_total` is a red herring, that means that no connection failed to be created, not that requests are not failing.

In fact the interesting part is that we keep getting more and more active connections, that is: things are not timing out somewhere, thus requests lock forever.

What I find concerning is that we did not see a single error reported in the logs.

(disclaimer: I'm involved in this testing)

**Comment by jranson** [comment] 2019-09-07 03:24
@vitovitolo I noticed you are using `bbolt` (awesome!). Investigating this, I found a few race conditions in both bbolt and memory cache types that can deadlock the mutex on certain URLs, causing them to hang and time out until trickster is bounced. I have submitted patches (PRs #274 and #277). This could possibly be the root cause for your issue, and possibly not. But if you don't identify a separate root cause before we release the next beta, hopefully you can confirm if this is resolved in the next beta release. Thanks to you and @pcarranza for trying the beta, contributing back to the project with issues and patches. We really appreciate it!

**Comment by jranson** [comment] 2020-01-17 23:21
@vitovitolo @pcarranza @ti-mo we have released Beta10 which includes the deadlock patches for BBolt and many other fixes. Would you mind trying this release to see if it mitigates your issue? Sorry for the delay on getting this patch into a release. We would love to know if this was the root cause for you and that it is all fixed up. I will leave this issue open until you provide a confirmation. Thank you again!

**Comment by jranson** [comment] 2020-02-10 20:12
Closing for now, as mentioned above we have made patches that hopefully (uncertain without more info from the reporter) correct this issue. As of now, we cannot reproduce following the mentioned fixes. If the GA release of Trickster 1.0 still exhibits this problem, please re-open the issue and we'll take another look

**Closed by jranson** 2020-02-10 20:12 UTC

**Comment by vitovitolo** [comment] 2020-08-12 07:05
@jranson sorry for the late response.

We did not update until yesterday because different reasons. Right now we're running trickster 1.12 with BBolt as main cache backend for one of our main production prometheus servers. Seems the bug is fixed. I'll let you know otherwise.

Thanks!
