### ISSUE TITLE
Using trickster causes grafana bar graph widths to fluctuate

### ISSUE THREAD

**Issue by frankh** [Comcast/trickster#60] opened 2018-06-21 12:11 UTC
Has anyone else got this problem? Trickster fixed my issues with graphs fluctuating wildly between refreshes, but now the bar widths themselves fluctuate.

It seems like graphana uses the distance between the first 2 points to get the width? could/should this be fixed?

**Comment by jranson** [comment] 2018-06-21 17:39
Hey @frankh  would you mind posting some screen shots to demonstrate the issue?  Thank you!

**Comment by roidelapluie** [comment] 2018-06-21 18:29
It is a bug in grafana.

Grafana itself now in master has removed the fluctuating graph problem.

**Comment by jranson** [comment] 2018-06-21 18:30
Closing as per Julien's note ^. Thank you!

**Closed by jranson** 2018-06-21 18:30 UTC

**Comment by roidelapluie** [comment] 2018-06-21 18:50
![bug](https://user-images.githubusercontent.com/291750/41739221-b4719ef6-7594-11e8-9c9d-169b656869a7.png)
FTR this is with prometheus+grafana master

**Comment by frankh** [comment] 2018-06-21 23:32
Thanks @roidelapluie, would you mind linking the grafana issue/pr/commit for this?

**Comment by aiman-alsari** [comment] 2019-08-08 15:21
Hi, I realise this is an old issue but it's happening to me now. I can hit refresh over and over and get differing bar widths on each refresh. I'm on Grafana 6.2.5.

My suspicion is that it is something to do with the "Step boundary normalization" stuff, as the width in grafana is based off the aggregation period, which shouldn't be changing on each refresh. If I take trickster out of the equation it all works fine.

**Comment by aiman-alsari** [comment] 2019-08-09 08:26
After some testing, I've found that the issue is still reproducible, but only on large time ranges > 12 hours. At a lower time interval the graphs look identical to vanilla prometheus.

**Comment by aiman-alsari** [comment] 2019-08-09 08:40
Disabling the fast-forward feature has no impact

**Comment by ti-mo** [comment] 2019-09-21 18:20
Adding another data point to this issue, also seems related to using fast-forward.
https://github.com/Comcast/trickster/issues/92

Trickster version: `0.1.10`
Grafana version: `6.3.5`

I'm using a heatmap to visualize a histogram over time, and the following graphical error occurs:

![image](https://user-images.githubusercontent.com/3214460/65377366-32b8c900-dcab-11e9-98af-e053ae49aacb.png)

The bars do not fill the whole width of their buckets. When this happens, the query response looks like this:

```
"url": "api/datasources/proxy/47/api/v1/query_range?query=sum(rate(traefik_backend_request_duration_seconds_bucket%7Bbackend%3D~%22backend-.*%22%2C%20protocol!%3D%22websocket%22%7D%5B300s%5D))%20by%20(le)&start=1569076500&end=1569087300&step=300"
            [
              1569087000,
              "7785.367134010938"
            ],
            [
              1569087300,
              "7747.348148148145"
            ],
            [
              1569087306,
              "7725.307407407405"
            ]
```

The last data point in the series is not aligned with the query step. Query directly against (another) Prometheus:

```
"url": "api/datasources/proxy/15/api/v1/query_range?query=sum(rate(traefik_backend_request_duration_seconds_bucket%7Bbackend%3D~%22backend-.*%22%2C%20protocol!%3D%22websocket%22%7D%5B300s%5D))%20by%20(le)&start=1569087300&end=1569088200&step=300"
            [
              1569087600,
              "0.28421052631578947"
            ],
            [
              1569087900,
              "0.2631578947368421"
            ],
            [
              1569088200,
              "0.28421052631578947"
            ]
```

I suspect this is an artifact caused by fast-forward, because selecting a fixed timespan in the past never causes this. From my limited understanding, fast-forward should only update the value associated with the last point in the series, the timestamp of the point should be fixed and aligned with the step value requested in the query.

Looking forward to being able to run a 1.x release!
