### ISSUE TITLE
Health endpoint pulls very large payload

### ISSUE THREAD

**Issue by raffraffraff** [Comcast/trickster#225] opened 2019-05-09 15:33 UTC
I just hit the /health endpoint with a curl and it spammed my terminal. So I directed it to a file and it produced 70mb of data. Is this expected? Seems ridiculously heavy.

**Comment by jranson** [comment] 2019-05-09 16:53
@raffraffraff Hi Paul, can you provide some more info (e.g., trickster version, etc). Thanks!

**Comment by raffraffraff** [comment] 2019-05-30 17:23
Sorry for the delay. I was using an older version (v0.1.7 I think). I've recently upgraded to the 1.0-beta5 and the problem is not only 'still there' but is returning far more data. Example:

```
curl -o /tmp/health -vvv localhost:9090/health                                                                                                                                                                                                                                            
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* About to connect() to localhost port 9090 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 9090 (#0)
> GET /health HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:9090
> Accept: */*
> 
  0     0    0     0    0     0      0      0 --:--:--  0:02:15 --:--:--     0< HTTP/1.1 200 OK
< Access-Control-Allow-Headers: Accept, Authorization, Content-Type, Origin
< Access-Control-Allow-Methods: GET, OPTIONS
< Access-Control-Allow-Origin: *
< Access-Control-Expose-Headers: Date
< Content-Type: application/json
< Date: Thu, 30 May 2019 16:45:03 GMT
< X-Accelerator: trickster 1.0.5
< Transfer-Encoding: chunked
< 
{ [data not shown]
100  126M    0  126M    0     0   823k      0 --:--:--  0:02:36 --:--:-- 5299k
100  875M    0  875M    0     0  3173k      0 --:--:--  0:04:42 --:--:-- 7727k
```

You read that correctly - it pulled 875mb of data. I'm running Trickster as follows:

Grafana --> Trickster --> Promxy

I use Promxy to send queries to various Prometheus & Thanos Query instances.

**Comment by raffraffraff** [comment] 2019-05-30 17:38
Its use of `/label/__name__/values` may be the issue? Would this be expected to return a huge data set if Trickster were fronting a very large multi-datacenter Thanos setup, with high cardinality metrics?

**Comment by jranson** [comment] 2019-05-31 13:45
@raffraffraff It's definitely possible that it could be due to the size of your label set. The reason we use that particular labels path is because Grafana also uses it to test connectivity when you add/update a datasource. For the beta7 release, I will change it to `/api/v1/query?query=up`, which accomplishes the same result and is guaranteed to return a small payload.

**Comment by jranson** [comment] 2019-06-11 13:56
@raffraffraff  this should be all fixed up in the next beta release which we'll cut later today (we have one more merge to come in first).

**Comment by raffraffraff** [comment] 2019-06-13 13:41
Just tested `curl -svvv localhost:9090/health` but got a 405
```
* About to connect() to localhost port 9090 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 9090 (#0)
> GET /health HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:9090
> Accept: */*
> 
< HTTP/1.1 405 Method Not Allowed
< Access-Control-Allow-Origin: *
< Content-Type: text/plain; charset=utf-8
< Date: Thu, 13 Jun 2019 13:33:28 GMT
< X-Accelerator: trickster 1.0.7
< X-Content-Type-Options: nosniff
< X-Trickster-Result: engine=HTTPProxy
< Content-Length: 19
< 
Method Not Allowed
* Connection #0 to host localhost left intact
Getting 405 Method Not Allowed
```

Trickster is working fine, this is happening because I'm using Trickster to cache for our Promxy service, and it doesn't seem to support the `query?query=up` method that you're using. I think I should open an issue on the Promxy project.

**Comment by raffraffraff** [comment] 2019-06-13 13:45
Looks like Promxy provides different endpoints: `/-/healthy` (returns "Prometheus is Healthy") and 
`/-/ready` (returns "Prometheus is Ready")

**Comment by jranson** [comment] 2019-06-13 14:43
I don't think it's an issue w/ Promxy at all, but I think we have root caused this and will have it fixed up in Beta 8. Work for that is going on on under `https://github.com/jranson/trickster/tree/1.0-httprpc`- and one of the things we'll to offer a configurable upstream health check URL.

**Comment by jranson** [comment] 2019-06-18 14:36
The root issue was that, in the change to `/api/v1/query=up` as the param for health, I sophomorically set that entire string to the `url.Path` instead of setting `url.Path = /api/v1/query` and `url.RawQuery = query=up`. We've PR'ed this minor fix separately for Beta8 releasing today, while a configurable hc url will be part of Beta9.

**Closed** 2019-06-18 21:40 UTC
Labels: Fixed in 1.0 Beta, Prometheus, performance
