### ISSUE TITLE
Trickster provokes grafana display quirks

### ISSUE THREAD

**Issue by sylr** [Comcast/trickster#92] opened 2018-10-11 09:17 UTC
I noticed a few grafana display bugs in my graphs which at first I blamed on Thanos but forgot I had a trickster in front of it.

Expected graph
![grafana-prometheus](https://user-images.githubusercontent.com/153052/46793562-50b14600-cd46-11e8-9612-e010a8e6ff76.png)

`Thanos + Trickster` graph
![grafana-thanos-2](https://user-images.githubusercontent.com/153052/46793574-5c047180-cd46-11e8-9a52-ac6543bfe8b7.png)

The data are the same but only come from different origin/path.

This only happens when I set the end of range to `now` in grafana. If fix the end of range to a fixed time I can't reproduce.

Taking a look at the data coming from `Prometheus` and `Thanos + Trickster` I got the following diff

![screenshot_15](https://user-images.githubusercontent.com/153052/46793719-b271b000-cd46-11e8-947b-56b1f0459e28.png)

As you can see the last timestamp is not aligned with the `step` in the `Thanos + Trickster` case and it confuses grafana's output.

Bypassing Trickster fixes the problem.

**Comment by juliusv** [comment] 2018-10-11 10:16
[disclaimer: I'm not heavily involved in Trickster, but saw this issue]

This seems to be due to Trickster's fast-forward feature: https://github.com/comcast/trickster#3-fast-forward - so it's sold as a feature, not a bug there.

I don't know if Grafana has a reasonable right to assume that Prometheus result data can only come back in the requested step interval. Probably the best thing would be to fix Grafana to support this, unless they have good reasons not to?

**Comment by SuperQ** [comment] 2018-10-11 10:58
Grafana recently (as of 5.2?) added some changes to the way it sends time ranges and steps, in order to reduce graph jitter for Prometheus users. It uses a default based on the "scrape interval" specified in the datasource config. This defaults to 15s.

But I don't think this would conflict too badly with Trickster's similar time alignments.

**Comment by sylr** [comment] 2018-10-11 11:03
I'm using grafana v5.2.3 and here the call that is made that retrieves unaligned last timestamp

```
api/datasources/proxy/44/api/v1/query_range?query=kube_deployment_status_replicas_unavailable%7Bcluster%3D~%22k8s6-euw-prod%22%2Cnamespace%3D~%22.*%22%2Cdeployment%3D~%22.*%22%7D%20%2F%20kube_deployment_status_replicas%7Bcluster%3D~%22k8s6-euw-prod%22%2Cnamespace%3D~%22.*%22%2Cdeployment%3D~%22.*%22%7D&start=1539244860&end=1539255720&step=60&timeout=60s
```

**Comment by sylr** [comment] 2018-10-22 14:39
SO I managed to get normal bars by disabling `fast-forward` feature.

However I still have a problem with queries involving a `delta()` function

With trickster :

![screenshot_16](https://user-images.githubusercontent.com/153052/47298636-93adcc00-d618-11e8-8f92-dedc3a8eac7f.png)

Without :

![screenshot_17](https://user-images.githubusercontent.com/153052/47298638-94def900-d618-11e8-818a-d2e08e5be229.png)

With the Grafana query inspector reveals that Trickster returns several times the first record of each series :

```patch
--- thanos
+++ thanos+trickster
@@ -2,7 +2,7 @@
   "xhrStatus": "complete",
   "request": {
     "method": "GET",
-    "url": "api/datasources/proxy/47/api/v1/query_range?query=delta(azure_batch_jobs_completed_total%7Benv%3D~%22prod%22%2Caccount%3D~%22placementeuwbatchprod%22%2Cjob_name%3D~%22Omega%20Line%20Ltd%7Cquick-estimate%22%7D%5B2m%5D)&start=1540215000&end=1540218720&step=120&timeout=60s"
+    "url": "api/datasources/proxy/44/api/v1/query_range?query=delta(azure_batch_jobs_completed_total%7Benv%3D~%22prod%22%2Caccount%3D~%22placementeuwbatchprod%22%2Cjob_name%3D~%22Omega%20Line%20Ltd%7Cquick-estimate%22%7D%5B2m%5D)&start=1540215000&end=1540218720&step=120&timeout=60s"
   },
   "response": {
     "status": "success",
@@ -28,6 +28,18 @@
               "0"
             ],
             [
+              1540215960,
+              "0"
+            ],
+            [
+              1540215960,
+              "0"
+            ],
+            [
+              1540215960,
+              "0"
+            ],
+            [
               1540216080,
               "0"
             ],
@@ -136,6 +148,18 @@
               "0"
             ],
             [
+              1540215960,
+              "0"
+            ],
+            [
+              1540215960,
+              "0"
+            ],
+            [
+              1540215960,
+              "0"
+            ],
+            [
               1540216080,
               "0"
             ],
```

**Comment by sylr** [comment] 2018-12-07 14:53
I can't reproduce with v0.1.5 so closing.

**Comment by jranson** [comment] 2018-12-07 14:57
@sylr did you try w/ Fast Forward enabled again and did that work as expected as well?

**Comment by sylr** [comment] 2018-12-07 15:01
Just tried with fast forwarded on and the problem with thin bars is still present.

**Comment by sylr** [comment] 2018-12-07 15:02
But I can't reproduce https://github.com/Comcast/trickster/issues/92#issuecomment-431855045

**Comment by sylr** [comment] 2018-12-11 09:45
I revised my previous comment I still can reproduce https://github.com/Comcast/trickster/issues/92#issuecomment-431855045

Without trickster:
![screenshot_26](https://user-images.githubusercontent.com/153052/49791926-c0858200-fd31-11e8-8289-0665b6189a82.png)

With trickster:
![screenshot_27](https://user-images.githubusercontent.com/153052/49791929-c24f4580-fd31-11e8-846e-319aa8660b9b.png)

**Comment by jranson** [comment] 2018-12-18 23:52
@sylr would you mind testing against trickster:0.1.6-rc1 and see if that clears up these artifacts? Thank you!

**Comment by sylr** [comment] 2018-12-19 15:51
@jranson https://github.com/Comcast/trickster/issues/92#issuecomment-431855045 seems gone!

**Comment by sylr** [comment] 2018-12-19 16:02
I've a lot of: 

```
1545218400 1545234600
1545219000 1545234600
1545219600 1545234600
1545220200 1545234600
1545220800 1545234600
1545221400 1545234600
1545222000 1545234600
1545222600 1545234600
1545223200 1545234600
1545223800 1545234600
1545224400 1545234600
```
in the logs so @jacksontj was right about https://github.com/Comcast/trickster/pull/114.

**Comment by sylr** [comment] 2018-12-20 14:57
I've got another problem now. With 0.1.6-rc1 query over a long range are truncated.

I'll try to investigate more if I have some time but right now I need to rollback to 0.1.5.

**Comment by jacksontj** [comment] 2019-01-08 18:04
@sylr when you get a minute, would you mind checking master now that the fix for #116 is merged in?

**Comment by jranson** [comment] 2019-01-08 18:06
@sylr I have tricksterio:trickster0.1.6-rc2 pushed to docker hub if that is easier for you to try out. Thanks again, and thanks to @jacksontj for sticking with this one!

**Comment by sylr** [comment] 2019-01-08 18:14
OK I will

**Closed** 2019-01-10 01:03 UTC
Labels: bug
