### ISSUE TITLE
Possible to read metrics in outside max_value_age_sec?

### ISSUE THREAD

**Issue by ninjaslothx** [Comcast/trickster#337] opened 2019-11-19 21:51 UTC
Is it possible to have trickster read in metrics further back in time than the cache will allow...but not cache?

Example we have metrics going back several years. 
90% of our dashboard usage is for 1week~. Trickster cache is great for this and is set to this size. 
However for us to query data outside this period we have to setup a datasource variable in grafana to change to "long term" bypassing trickster and going direct to thanos-query. 
Is it possible to have trickster pull in what it can from the cache and otherwise run a non cached query if it exceeds the cache age?

**Comment by jranson** [comment] 2019-11-19 21:53
hi @ninjaslothx what version of Trickster do you use? The latest stable release (0.1.x) as well as the 1.0 beta (and several releases prior) work the way you are asking without needing additional data sources.

**Comment by ninjasloth22** [comment] 2019-12-11 22:51
Currently on 0.1.10
Is there a setting required to enable this? I am still getting only metrics up to the cache age.

![image](https://user-images.githubusercontent.com/14971594/70667287-581b0900-1cd5-11ea-8ecd-48b9d698b1e9.png)

My config looks like the following:
`[main]

[proxy_server]

[cache]
cache_type = 'filesystem'
    [cache.filesystem]
    cache_path = '/opt/data/trickster/cache'

[origins]
    [origins.default]
    origin_url = 'https://thanosurl'
    api_path = '/api/v1'
    max_value_age_secs = 432000

[metrics]
listen_port = 8082

[profiler]

[logging]
log_level = 'info'
log_file = '/var/log/trickster.log'`

**Comment by jranson** [comment] 2020-01-17 23:30
Hi @ninjaslothx, would you mind trying this on the 1.0 Beta 10 that was just released (or beta 9 if you're not feeling adventurous). As we are primarily focused on 1.0 in advance of the GA release (hopefully next month!), and as of today the 1.0.x codebase is merged to `master`, so the older 0.1.x codebase can no longer be maintained.

**Comment by ninjaslothx** [comment] 2020-01-21 19:18
Hey @jranson, I upgraded to Beta 10. This has indeed resolved the issue! 
I have however run into a new issue where after the first query or two are run it fails to run any new queries. 
The only fix is to stop the service and delete the cache. However the same scenario happens next run. 
If I try to restart the service without deleting the cache I get this.

`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x9182e3]
goroutine 1 [running]:
github.com/Comcast/trickster/internal/cache/index.(*Index).GetExpiration(0x0, 0xb60d4c, 0xb, 0x8b3, 0xc0000acfb3, 0x0)
        /private/build/trickster/internal/cache/index/index.go:209 +0x43
github.com/Comcast/trickster/internal/cache/filesystem.(*Cache).retrieve(0xc00019b2c0, 0xb60d4c, 0xb, 0xb50000, 0x6, 0xc000023270, 0xd, 0x0, 0x0, 0x0)
        /private/build/trickster/internal/cache/filesystem/filesystem.go:129 +0x587
github.com/Comcast/trickster/internal/cache/filesystem.(*Cache).Connect(0xc00019b2c0, 0xc00019b2c0, 0xc00016a2f8)
        /private/build/trickster/internal/cache/filesystem/filesystem.go:56 +0x28c
github.com/Comcast/trickster/internal/cache/registration.NewCache(0xc000192093, 0x7, 0xc000089860, 0x1108f54, 0x1)
        /private/build/trickster/internal/cache/registration/registration.go:74 +0xbb
github.com/Comcast/trickster/internal/cache/registration.LoadCachesFromConfig()
        /private/build/trickster/internal/cache/registration/registration.go:50 +0xbe
main.main()
        /private/build/trickster/cmd/trickster/main.go:87 +0x6a7`

However in the context of this issue, please feel free to close and I'll do some more testing and open a new issue if required.

**Comment by jranson** [comment] 2020-01-21 19:21
Thanks for this new report. Panics are always bad and a bug!  We'll try to reproduce this, root cause it, and get it fixed up for you.  Would you mind trying with a memory cache or bbolt? that way we can isolate quickly whether it's related to the filesystem cache type or something higher up in the chain. Thanks again!

**Comment by ninjaslothx** [comment] 2020-01-21 20:40
Memory cache works without issue. It would certainly appear to be related to the filesystem cache. 
Let me know if you would like me to run any more tests!

**Comment by jranson** [comment] 2020-02-06 05:39
@ninjasloth22 the filesystem and bbolt panics should now be resolved in the latest release, which is 1.0.0-rc1. Please let me know if you find everything to be fixed up and we'll close out this issue. Thanks again for the report!

**Comment by jranson** [comment] 2020-02-20 18:32
As we think this is resolved, but havent gotten confirmation from the reporter after 2 weeks, i will close for now. Please re-open or file another issue if you have any more problems. thanks for the report!

**Closed by jranson** 2020-02-20 18:32 UTC
Labels: question
